// Code generated by "stringer -type=BlockColor"; DO NOT EDIT

package game

import "fmt"

const _BlockColor_name = "RedPurpleBlueCyanGreenYellowBlockColorCount"

var _BlockColor_index = [...]uint8{0, 3, 9, 13, 17, 22, 28, 43}

func (i BlockColor) String() string {
	if i < 0 || i >= BlockColor(len(_BlockColor_index)-1) {
		return fmt.Sprintf("BlockColor(%d)", i)
	}
	return _BlockColor_name[_BlockColor_index[i]:_BlockColor_index[i+1]]
}
