// Code generated by "stringer -type=BoardState"; DO NOT EDIT

package game

import "fmt"

const _BoardState_name = "BoardEnteringBoardRisingBoardGameOverBoardExiting"

var _BoardState_index = [...]uint8{0, 13, 24, 37, 49}

func (i BoardState) String() string {
	if i < 0 || i >= BoardState(len(_BoardState_index)-1) {
		return fmt.Sprintf("BoardState(%d)", i)
	}
	return _BoardState_name[_BoardState_index[i]:_BoardState_index[i+1]]
}
