// Code generated by "stringer -type=GameState"; DO NOT EDIT

package game

import "fmt"

const _GameState_name = "GameInitialGamePlayingGamePausedGameExiting"

var _GameState_index = [...]uint8{0, 11, 22, 32, 43}

func (i GameState) String() string {
	if i < 0 || i >= GameState(len(_GameState_index)-1) {
		return fmt.Sprintf("GameState(%d)", i)
	}
	return _GameState_name[_GameState_index[i]:_GameState_index[i+1]]
}
