// Code generated by "stringer -type=HUDItem"; DO NOT EDIT

package game

import "fmt"

const _HUDItem_name = "HUDItemSpeedHUDItemTimeHUDItemScore"

var _HUDItem_index = [...]uint8{0, 12, 23, 35}

func (i HUDItem) String() string {
	if i < 0 || i >= HUDItem(len(_HUDItem_index)-1) {
		return fmt.Sprintf("HUDItem(%d)", i)
	}
	return _HUDItem_name[_HUDItem_index[i]:_HUDItem_index[i+1]]
}
