// Code generated by "stringer -type=MarkerState"; DO NOT EDIT

package game

import "fmt"

const _MarkerState_name = "MarkerNoneMarkerShowing"

var _MarkerState_index = [...]uint8{0, 10, 23}

func (i MarkerState) String() string {
	if i < 0 || i >= MarkerState(len(_MarkerState_index)-1) {
		return fmt.Sprintf("MarkerState(%d)", i)
	}
	return _MarkerState_name[_MarkerState_index[i]:_MarkerState_index[i+1]]
}
