// Code generated by "stringer -type=MenuID"; DO NOT EDIT

package game

import "fmt"

const _MenuID_name = "MenuIDMainMenuIDNewGameMenuIDPausedMenuIDGameOver"

var _MenuID_index = [...]uint8{0, 10, 23, 35, 49}

func (i MenuID) String() string {
	if i < 0 || i >= MenuID(len(_MenuID_index)-1) {
		return fmt.Sprintf("MenuID(%d)", i)
	}
	return _MenuID_name[_MenuID_index[i]:_MenuID_index[i+1]]
}
