// Code generated by "stringer -type=MenuChoice"; DO NOT EDIT

package game

import "fmt"

const _MenuChoice_name = "MenuChoiceEasyMenuChoiceMediumMenuChoiceHard"

var _MenuChoice_index = [...]uint8{0, 14, 30, 44}

func (i MenuChoice) String() string {
	if i >= MenuChoice(len(_MenuChoice_index)-1) {
		return fmt.Sprintf("MenuChoice(%d)", i)
	}
	return _MenuChoice_name[_MenuChoice_index[i]:_MenuChoice_index[i+1]]
}
