// Code generated by "stringer -type=MenuChoiceID"; DO NOT EDIT

package game

import "fmt"

const _MenuChoiceID_name = "MenuEasyMenuMediumMenuHard"

var _MenuChoiceID_index = [...]uint8{0, 8, 18, 26}

func (i MenuChoiceID) String() string {
	if i >= MenuChoiceID(len(_MenuChoiceID_index)-1) {
		return fmt.Sprintf("MenuChoiceID(%d)", i)
	}
	return _MenuChoiceID_name[_MenuChoiceID_index[i]:_MenuChoiceID_index[i+1]]
}
