// Code generated by "stringer -type=MenuItemType"; DO NOT EDIT

package game

import "fmt"

const _MenuItemType_name = "MenuItemTypeChoiceMenuItemTypeSlider"

var _MenuItemType_index = [...]uint8{0, 18, 36}

func (i MenuItemType) String() string {
	if i >= MenuItemType(len(_MenuItemType_index)-1) {
		return fmt.Sprintf("MenuItemType(%d)", i)
	}
	return _MenuItemType_name[_MenuItemType_index[i]:_MenuItemType_index[i+1]]
}
