// Code generated by "stringer -type=MenuID"; DO NOT EDIT

package game

import "fmt"

const _MenuID_name = "MenuMainMenuNewGameMenuPausedMenuGameOver"

var _MenuID_index = [...]uint8{0, 8, 19, 29, 41}

func (i MenuID) String() string {
	if i >= MenuID(len(_MenuID_index)-1) {
		return fmt.Sprintf("MenuID(%d)", i)
	}
	return _MenuID_name[_MenuID_index[i]:_MenuID_index[i+1]]
}
