// Code generated by "stringer -type=MenuItem"; DO NOT EDIT

package game

import "fmt"

const _MenuItem_name = "MenuItemContinueGameMenuItemNewGameMenuItemExit"

var _MenuItem_index = [...]uint8{0, 20, 35, 47}

func (i MenuItem) String() string {
	if i < 0 || i >= MenuItem(len(_MenuItem_index)-1) {
		return fmt.Sprintf("MenuItem(%d)", i)
	}
	return _MenuItem_name[_MenuItem_index[i]:_MenuItem_index[i+1]]
}
