// Code generated by "stringer -type=MenuTitle"; DO NOT EDIT

package game

import "fmt"

const _MenuTitle_name = "MenuTitleInitialMenuTitlePausedMenuTitleGameOver"

var _MenuTitle_index = [...]uint8{0, 16, 31, 48}

func (i MenuTitle) String() string {
	if i < 0 || i >= MenuTitle(len(_MenuTitle_index)-1) {
		return fmt.Sprintf("MenuTitle(%d)", i)
	}
	return _MenuTitle_name[_MenuTitle_index[i]:_MenuTitle_index[i+1]]
}
