// Code generated by "stringer -type=SelectorState"; DO NOT EDIT

package game

import "fmt"

const _SelectorState_name = "SelectorStaticSelectorMovingUpSelectorMovingDownSelectorMovingLeftSelectorMovingRight"

var _SelectorState_index = [...]uint8{0, 14, 30, 48, 66, 85}

func (i SelectorState) String() string {
	if i < 0 || i >= SelectorState(len(_SelectorState_index)-1) {
		return fmt.Sprintf("SelectorState(%d)", i)
	}
	return _SelectorState_name[_SelectorState_index[i]:_SelectorState_index[i+1]]
}
