// Code generated by "stringer -type=Sound"; DO NOT EDIT

package audio

import "fmt"

const _Sound_name = "SoundMoveSoundSelectSoundSwapSoundClearSoundThud"

var _Sound_index = [...]uint8{0, 9, 20, 29, 39, 48}

func (i Sound) String() string {
	if i < 0 || i >= Sound(len(_Sound_index)-1) {
		return fmt.Sprintf("Sound(%d)", i)
	}
	return _Sound_name[_Sound_index[i]:_Sound_index[i+1]]
}
